/**
 * List of terms to censor
 *
 * Credit: https://github.com/mourner/bullshit.js/blob/master/src/terms.js
 *
 * Last Updated 2019-10-20
 */

export default [
  "((business|client|community|culture|customer|data|goal|intelligence|market" +
    "|process|quality|results|role|sales|subject|service|user)" +
    ".(centric(ity)?|facing|oriented|driven|focused|assessment|service|process))",
  "(benefit|gap) analysis",
  "(high|mass).impact",
  "(inflat|redeem)able value",
  "(mission|time).critical",
  "(new|next|second).(level|gen|generation)",
  "(serial )?entrepreneurs?",
  "(s|p)aas",
  "(total cost of )?ownership",
  "24/7",
  "a[-/]b testing",
  "accelerate",
  "acquisition",
  "act in time",
  "action items?",
  "advantages?",
  "agents?",
  "aggregate",
  "agile",
  "ai",
  "all.in.one",
  "all.new",
  "analytics?",
  "application service providers?",
  "artificial intelligence",
  "as a service",
  "assets?",
  "at (your|their) fingertips",
  "augmented",
  "authoritative",
  "automated",
  "autonomous",
  "award.winning",
  "b2(b|c)",
  "back to the drawing board",
  "ball.?park",
  "band.aid",
  "bandwidth",
  "behavioral",
  "bespoke",
  "best.in.class",
  "best.of.breed",
  "best.practice",
  "big picture",
  "big thinkers?",
  "big.data",
  "blazing(ly)? fast",
  "block.?chain",
  "boost(s|ing)?",
  "bottom.line",
  "bottom.up",
  "brain.?dump",
  "brain.?storm(ing)?",
  "brand(s?|ing|ed)",
  "bulletproof",
  "burn.rates?",
  "business( cases| plans)",
  "buzz",
  "call to action",
  "capabilit(y|ies)",
  "capitali(s|z)e",
  "centers? of excellence",
  "challenges?",
  "change agents?",
  "circle the wagons",
  "client-centered",
  "client-centric",
  "client-focused",
  "cloud native",
  "cloud",
  "cloudify",
  "collaborat(e|ion|ive)s?",
  "committee",
  "communicat(e|ion)s?",
  "company-employee.fit",
  "compelling",
  "competitive( advantage)?",
  "complex(ity)?",
  "comprehensive",
  "connect the dots",
  "connected systems?",
  "container orchestration",
  "containerizat(e|ion|ing)",
  "content management",
  "contextual(ly)?",
  "contingency plans?",
  "control groups?",
  "control plane",
  "convergence",
  "convergent",
  "conversions?",
  "core business",
  "core competenc(y|ies)",
  "core.to.edge",
  "cosmic",
  "cost control",
  "cost-effective",
  "cost/benefit",
  "craftsmanship",
  "critical path",
  "crm",
  "cross.sell",
  "crowd.?(fund(s?|ed|ing)|sourc(ed|e|ing))",
  "crypto(?!graphy).\\w+",
  "crypto.currency",
  "customer obsession",
  "cutting.edge",
  "cyber",
  "dashboarding",
  "dashboards?",
  "data mining",
  "de-?dupe",
  "decentrali(s|z)ed",
  "deep dive",
  "deep learning",
  "delight",
  "deliverables?",
  "demographic",
  "demystify",
  "demystifying",
  "deployless",
  "devops",
  "digital transformation",
  "disrupt(ive|tor)?",
  "distributed ledgers?",
  "dollar.productive",
  "downsi(s|z)e",
  "drill down",
  "drink the kool-aid",
  "drop the ball",
  "drop.?in",
  "due dilligence",
  "dynamic(s|ally)?",
  "e-?(business|commerce|tailers)",
  "early.stage",
  "eas(y|ily)",
  "ecosystems?",
  "efficien(t|cy)",
  "effortless(ly)?",
  "elaboration",
  "elastic",
  "elephant in the room",
  "elevator pitch",
  "emerging markets?",
  "empower(ing|ment|s)?",
  "enabl(e|ing)",
  "enablement",
  "end of the day",
  "end.to.end",
  "engag(e|ing)",
  "engage(ments?)?",
  "engulf",
  "enhanced?",
  "enterprise",
  "erp",
  "estimate",
  "eta",
  "etched in stone",
  "evolution",
  "exceed expectations",
  "exclusive(ly)?",
  "exhaustive",
  "expedite",
  "experiences",
  "expertise",
  "experts?",
  "exposure",
  "extended reality",
  "extraordinary",
  "facilitat(e|or)",
  "fast track",
  "fault.tolerant",
  "first.to.market",
  "flexibility",
  "flux",
  "fly( |-)wheel",
  "foot view",
  "forward-thinking",
  "four pillars",
  "frictionless",
  "front lines",
  "frustration[- ]free",
  "full benefit",
  "functional",
  "future.proof",
  "futurist",
  "game changer",
  "game plan",
  "global(ly)?",
  "go public",
  "go.to.market",
  "goals?",
  "god-speed",
  "going forward",
  "granular",
  "ground.?breaking",
  "guidance",
  "guru",
  "hackathon",
  "hacker( mindset)?",
  "happiness manage(ment|rs?)",
  "hardball",
  "heavy.lifting",
  "herding cats",
  "hidden.gem",
  "hidden.meaning",
  "high availability",
  "high capacity",
  "high.level",
  "highly.scalable",
  "hive ?mind",
  "holistic",
  "hybrid environments?",
  "hyper.personalization",
  "hyperconverged",
  "impactful",
  "impeccable",
  "in a nutshell",
  "incent",
  "incentivi(s|z)e",
  "increase the odds",
  "incredibl(e|y)",
  "influencers?",
  "influx",
  "innovat(e|ed|ion|ive|ing|or)s?",
  "insights?",
  "inspir(e|ing|ation)",
  "integrat(e|ed|ion)s?",
  "intellectual property",
  "internet of things",
  "intuitive",
  "iot",
  "key results?",
  "kickstart(er|ed)?s?",
  "killjoy",
  "knowledge.(base|transfer|sharing)",
  "kpis?",
  "landing pages?",
  "lead the field",
  "leaders?",
  "leadership",
  "leading",
  "learnings",
  "legacy",
  "lessons learned",
  "level (the )? playing field",
  "level set",
  "leverag(e|ing)",
  "lifecycle",
  "look.(&|and).feel",
  "low.hanging fruit",
  "m2m",
  "machine learning",
  "made simple",
  "magical",
  "market (chang(er|ing)|leader|window|simplified)",
  "market.ready",
  "marketing collateral",
  "maximi(s|z)e",
  "meaningful( client | )interactions?",
  "measurements?",
  "methodolog(y|ies)",
  "metrics",
  "middleware",
  "milestone",
  "military.grade encryption",
  "mind ?share",
  "mind ?shower",
  "mind-boggling",
  "mindset",
  "ml",
  "moneti(s|z)e",
  "mov(e|ing) (fast|forward)",
  "multi-?tenant(ed)?",
  "multifaceted",
  "multitask(ing?)",
  "negotiated",
  "networking",
  "new.breed",
  "new.economy",
  "niches?",
  "ninja",
  "ninja",
  "no-brainer",
  "non-traditional management",
  "objectives",
  "occupy the field",
  "off.site",
  "off.the.(radar|shelf)",
  "on board",
  "on the (back end|radar screen|same page|house)",
  "on.premises?",
  "one to one",
  "opportunit(y|ies)",
  "optimal",
  "orthogonal",
  "out(side)?.of.the.(box|loop)",
  "outperform",
  "outsourc(e|ed|ing)",
  "outstanding",
  "paradigms?( shift)?",
  "partner(ships?)?",
  "patents?",
  "performance indicators",
  "personaliz(e|ed|ation)",
  "perspective",
  "phased approach",
  "phases?",
  "pioneers",
  "pipeline",
  "pivot",
  "planning horizon",
  "platforms?",
  "plug.?in",
  "potentials?",
  "powerful",
  "prioriti(s|z)ed?",
  "proactive",
  "problem space",
  "processes",
  "production.ready",
  "productivity",
  "profit(ability)?",
  "prominent",
  "promotion",
  "promotional collateral",
  "proof.of.concept",
  "proprietary",
  "purpose.built",
  "push the envelope",
  "push.back",
  "pushing on open doors",
  "quick wins?",
  "rais(e|ing) the bar",
  "ramp.up",
  "ravishing",
  "reach out",
  "reactivation",
  "real.time",
  "real.world",
  "reconfigure",
  "red flags?",
  "redefin(e|ed|ing)",
  "reengineering",
  "reinvent(ing)? the(.square)? wheel",
  "reinvigorate",
  "relationship management",
  "relevance",
  "repurpose",
  "resilien(ce|cy|t)",
  "resource allocation",
  "responsive",
  "restructuring",
  "retention",
  "return on investment",
  "reus(e|ability)",
  "reverse.engineer",
  "revisit",
  "revolution",
  "rich",
  "road ?map",
  "robust",
  "rock.?star",
  "roi",
  "run the numbers",
  "sacrific(e|es|ing)",
  "scal(e|es|ing|ability)",
  "scenarios?",
  "scope",
  "scrum( master)?",
  "seamless",
  "search engine optimization",
  "secret sauce",
  "segments?",
  "self-managed team",
  "seo",
  "serverless",
  "service mesh",
  "shareholder value",
  "significant(ly)?",
  "single-source responsibility",
  "skill ?sets?",
  "smart(er)?",
  "smoke (&|and) mirrors",
  "social(.media|.gaming|.networks?)",
  "solidality",
  "sophisticated",
  "soup to nuts",
  "sow",
  "spatial.computing",
  "stakeholders?",
  "start.up?",
  "state.of.the.art",
  "statement of work",
  "step.changes?",
  "sticky-?ness",
  "story points?",
  "strateg(y|ic|ize|ise)",
  "streamlin(ed|e|ing)",
  "success(ful)?",
  "super(critical|star|nova)",
  "sustainab(le|ility)",
  "synerg(y|ies|ized|i)",
  "tailwinds?",
  "take offline",
  "talented",
  "talking points",
  "target (audience|group)",
  "targeted",
  "tasked",
  "tco",
  "team.building",
  "team.player",
  "teamwork",
  "technolog(y|ies)",
  "that being said",
  "throughput",
  "time.to.awesome",
  "time.to.market",
  "timelines?",
  "top.down",
  "top.of.the.game",
  "total quality",
  "touch.base",
  "touchpoints?",
  "traction",
  "transfor(m|ming)",
  "trends?",
  "truths?",
  "turnkey",
  "ultimate",
  "uncover",
  "unicorn",
  "unique approach",
  "unlimited.holidays",
  "up-?sell",
  "up.to.speed",
  "upside",
  "user funnels?",
  "user.experience",
  "user.friendly",
  "utili(s|z)(e|ation)",
  "value.add(ed)?",
  "valueable",
  "venture",
  "venturing",
  "vertical market",
  "viral",
  "virtual(ization|isation)?",
  "visibility",
  "visio(n|nary)",
  "walk the talk",
  "wearable",
  "web.enabled",
  "win-win",
  "wisdom of crowds",
  "with due respect",
  "with ease",
  "wizards?",
  "workflows?",
  "workloads?",
  "world a better place",
  "world.?class",
  "wow.factor",
  "xfn",
  "you've never seen (a|an) \\w+",
]
